---
- name: Applica configurazione ai server
  hosts: all
  become: true

  vars:
    # Dominio pubblico su cui l'applicazione è pubblicata
    # Questo dominio deve risolvere all'host su cui viene
    # gira il container di frontend (nginx-letsencrypt).
    app_domain: "spid-test.spc-app1.teamdigitale.it"

    # Riferimento email dell'amministratore
    admin_email: "federico@teamdigitale.governo.it"

    # Backend del layer applicativo.
    # Attualmente corrisponde al container applicativo ma
    # può essere un host esterno raggiungibile dal server di
    # frontend.
    app_backend_url: "http://app-backend:8080"

    # Prefisso applicativo protetto da autenticazione SPID.
    app_prefix: "/app"

  roles:
    - name: docker

    - name: app-backend
      tags: app-backend

    - name: shibboleth
      tags: shibboleth
      app_backend_container: app-backend

    - name: letsencrypt
      tags: letsencrypt
      shibboleth_container: shibboleth-nginx
