---
- name: "Make sure shibboleth-nginx log directory exist (supervisor)"
  file: path=/opt/shibboleth-nginx/log/supervisor state=directory

- name: "Make sure shibboleth-nginx log directory exist (nginx)"
  file: path=/opt/shibboleth-nginx/log/nginx state=directory

- name: "Make sure shibboleth-nginx etc directory exist"
  file: path=/opt/shibboleth-nginx/etc state=directory

- name: "Upload shibboleth config (extra)"
  copy: src=shibboleth-spid dest=/opt/shibboleth-nginx/

- name: "Upload shibboleth config (shibboleth2.xml)"
  template: src=shibboleth2.xml.j2 dest=/opt/shibboleth-nginx/shibboleth2.xml

- name: "Upload shibboleth config (nginx)"
  template: src=shibboleth-nginx-default.conf.j2 dest=/opt/shibboleth-nginx/shibboleth-nginx-default.conf

- name: "Make sure shibboleth-nginx container is restarted"
  docker_container:
    name: shibboleth-nginx
    image: virtualstaticvoid/shibboleth-nginx
    recreate: true
    links:
      - "{{ app_backend_container }}:{{ app_backend_container }}"
    volumes:
      - "/opt/shibboleth-nginx/log:/var/log"
      - "/opt/shibboleth-nginx/shibboleth-nginx-default.conf:/etc/nginx/conf.d/default.conf"
      - "/opt/shibboleth-nginx/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml"
      - "/opt/shibboleth-nginx/shibboleth-spid/attribute-map.xml:/etc/shibboleth/attribute-map.xml"
      - "/opt/shibboleth-nginx/shibboleth-spid/attribute-policy.xml:/etc/shibboleth/attribute-policy.xml"
      - "/opt/shibboleth-nginx/shibboleth-spid/protocols.xml:/etc/shibboleth/protocols.xml"
      - "/opt/shibboleth-nginx/shibboleth-spid/security-policy.xml:/etc/shibboleth/security-policy.xml"
      - "/opt/shibboleth-nginx/agid-spid-metadata-signed.xml:/etc/shibboleth/spidMetadata.xml"
      - "/opt/shibboleth-nginx/shibboleth-spid/spid-idp-metadata:/etc/shibboleth/spid-idp-metadata"
      - "{{ shibboleth_credentials_key }}:/etc/shibboleth/certs/spid-signature.key:ro"
      - "{{ shibboleth_credentials_cert }}:/etc/shibboleth/certs/spid-signature.cer:ro"
